server:
  port: 9091

spring:
  application:
    name: Product Microservice
  data:
    mongodb:
      host: localhost
      port: 27017
      database: shopping
  profiles:
    active: local

product:
  currencies:
    - INR
    - USD
    - EUR

---
spring:
  config:
    activate:
      on-profile:
        - local
  application:
    name: Product Microservice(Local Env)


